# Azure DevOps Pipeline for React App
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '18.x'

stages:
- stage: Build
  displayName: 'Build and Test'
  jobs:
  - job: BuildJob
    displayName: 'Build'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '$(nodeVersion)'
      displayName: 'Install Node.js'

    - script: |
        cd frontend-vanilla
        npm ci
      displayName: 'Install dependencies'

    - script: |
        cd frontend-vanilla
        npm run build
      displayName: 'Build application'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: 'frontend-vanilla/dist'
        artifactName: 'dist'

- stage: Deploy
  displayName: 'Deploy to Azure Static Web Apps'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployJob
    displayName: 'Deploy'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureStaticWebApp@0
            inputs:
              app_location: 'frontend-vanilla/dist'
              api_location: ''
              output_location: ''
              azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
