name: Daily Crypto Sentiment Update

on:
  schedule:
    # Run daily at 6:00 AM UTC
    - cron: '0 6 * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-sentiment:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'
          
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt
          
      - name: Run daily sentiment update
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
        run: |
          cd backend
          python cron_job.py
          
      - name: Notify on failure
        if: failure()
        run: |
          echo "Daily update failed. Check logs for details."
          # Add notification logic here (Slack, email, etc.)